export enum ServerEvents {
  FRIEND_REQUEST_CREATED = "friendrequest.create",
  FRIEND_REQUEST_CANCELED = "friendrequest.cancel",
  FRIEND_REQUEST_ACCEPTED = "friendrequest.accepted",
  FRIEND_REQUEST_REJECTED = "friendrequest.rejected",
  FRIEND_REMOVED = "friend.removed",
  CONVERSATION_CREATED = "conversation.create",
  CONVERSATION_UPDATED = "conversation.update",
  MESSAGE_CREATED = "message.create",
  MESSAGE_DELETED = "message.delete",
  MESSAGE_UPDATED = "message.update",
  GET_ONLINE_FRIENDS = "onlineFriends.get",
  NOTIFY_FRIENDS = "notifyFriends",
  NEW_NOTIFICATIONS = "notifications",
}

export enum ClientEvents {
  GET_ONLINE_FRIENDS = "getOnlineFriends",
  TYPING_START = "typingStart",
  TYPING_STOP = "typingStop",
  CONVERSATION_JOIN = "onConversationJoin",
  CONVERSATION_LEAVE = "onConversationLeave",
  VIDEO_CALL_INITIATE = "videoCallInitiate",
  VIDEO_CALL_ACCEPTED = "videoCallAccepted",
  VIDEO_CALL_REJECTED = "videoCallRejected",
  VIDEO_CALL_HANG_UP = "videoCallHangUp",
  VOICE_CALL_INITIATE = "voiceCallInitiate",
  VOICE_CALL_ACCEPTED = "voiceCallAccepted",
  VOICE_CALL_REJECTED = "voiceCallRejected",
  VOICE_CALL_HANG_UP = "voiceCallHangUp",
  UPDATE_REMOTE_STREAM = "updateRemoteStream",
}

export enum WebsocketEvents {
  FRIEND_REQUEST_RECEIVED = "onFriendRequestReceived",
  FRIEND_REQUEST_CANCELLED = "onFriendRequestCancelled",
  FRIEND_REQUEST_ACCEPTED = "onFriendRequestAccepted",
  FRIEND_REQUEST_REJECTED = "onFriendRequestRejected",
  FRIEND_REMOVED = "onFriendRemoved",
  CONVERSATION_CREATED = "onConversation",
  CONVERSATION_UPDATED = "onConversationUpdate",
  MESSAGE_CREATED = "onMessage",
  MESSAGE_DELETED = "onMessageDelete",
  MESSAGE_UPDATED = "onMessageUpdate",
  ON_TYPING_START = "onTypingStart",
  ON_TYPING_STOP = "onTypingStop",
  VIDEO_CALL = "onVideoCall",
  VOICE_CALL = "onVoiceCall",
  USER_UNAVAILABLE = "onUserUnavailable",
  VIDEO_CALL_ACCEPTED = "onVideoCallAccepted",
  VIDEO_CALL_REJECTED = "onVideoCallRejected",
  VIDEO_CALL_HANG_UP = "onVideoCallHangUp",
  VOICE_CALL_ACCEPTED = "onVoiceCallAccepted",
  VOICE_CALL_REJECTED = "onVoiceCallRejected",
  VOICE_CALL_HANG_UP = "onVoiceCallHangUp",
  UPDATE_REMOTE_STREAM = "onUpdateRemoteStream",
  NEW_NOTIFICATIONS = "onMessageNotifications",
}

export enum Routes {
  AUTH = "auth",
  USERS = "users",
  FRIENDS = "friends",
  FRIEND_REQUESTS = "friends/requests",
  UPLOAD = "upload",
  CONVERSATIONS = "conversations",
  MESSAGES = "conversations/:id/messages",
  NOTIFICATIONS = "notifications",
}
