import Head from "next/head";
import Link from "next/link";
import { FiDownload } from "react-icons/fi";
import { GoThreeBars } from "react-icons/go";
import { RxCross2 } from "react-icons/rx";
import { BsTwitter, BsInstagram, BsFacebook, BsYoutube } from "react-icons/bs";
import { gintoFont } from "./_app";
import { useState } from "react";

export default function Home() {
  const [isOpen, setIsOpen] = useState(false);
  return (
    <div className={`${isOpen && "h-screen overflow-hidden"}`}>
      <Head>
        <title>Discord</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={"relative bg-[#404eed] text-white"}>
        <header className="flex justify-center">
          <nav className="relative z-10 flex h-[80px] w-full max-w-[1260px] items-center px-5 md:px-[40px] lg:justify-between">
            <Link href="/">
              <img
                src="/logos/small_logo_white_RGB.svg"
                width={124}
                height={36}
              />
            </Link>
            <ul className="hidden items-center font-semibold lg:flex">
              <li className="m-2.5 p-2.5 hover:underline">
                <Link href="/">Download</Link>
              </li>
              <li className="m-2.5 p-2.5 hover:underline">
                <Link href="/">Nitro</Link>
              </li>
              <li className="m-2.5 p-2.5 hover:underline">
                <Link href="/">Discover</Link>
              </li>
              <li className="m-2.5 p-2.5 hover:underline">
                <Link href="/">Safety</Link>
              </li>
              <li className="m-2.5 p-2.5 hover:underline">
                <Link href="/">Support</Link>
              </li>
              <li className="m-2.5 p-2.5 hover:underline">
                <Link href="/">Blog</Link>
              </li>
              <li className="m-2.5 p-2.5 hover:underline">
                <Link href="/">Careers</Link>
              </li>
            </ul>
            <Link
              href="/login"
              className="hover:shadow-button ml-auto rounded-3xl bg-white px-4 py-2 text-sm font-medium text-[#23272a] transition hover:text-brand lg:ml-0"
            >
              Login
            </Link>
            <div
              onClick={() => setIsOpen(false)}
              className={`absolute top-0 left-0 z-[19] hidden h-screen w-screen bg-black/40 lg:!hidden ${
                isOpen && "!block"
              }`}
            />
            <div
              className={`absolute top-0 bottom-0 right-[-300px] z-[20] flex h-screen flex-col items-start rounded-tl-lg rounded-bl-lg bg-white p-6 py-8 text-[#23272a] transition-all duration-300 ease-out lg:hidden ${
                isOpen && "right-0"
              }`}
            >
              <Link
                href="/"
                className="w-full min-w-[250px] border-b border-gray-200 pb-8"
              >
                <img
                  src="/logos/small_logo_black_RGB.svg"
                  width={124}
                  height={36}
                />
              </Link>
              <ul className="mt-4 flex w-full flex-col">
                <li className="rounded bg-gray-100 p-2 px-4 text-sky-400">
                  <Link className="hover:underline" href="/">
                    Home
                  </Link>
                </li>
                <li className="rounded px-4 py-2">
                  <Link className="hover:underline" href="/">
                    Download
                  </Link>
                </li>
                <li className="rounded px-4 py-2">
                  <Link className="hover:underline" href="/">
                    Nitro
                  </Link>
                </li>
                <li className="rounded px-4 py-2">
                  <Link className="hover:underline" href="/">
                    Discover
                  </Link>
                </li>
                <li className="rounded px-4 py-2">
                  <Link className="hover:underline" href="/">
                    Safety
                  </Link>
                </li>
                <li className="rounded px-4 py-2">
                  <Link className="hover:underline" href="/">
                    Mod academy
                  </Link>
                </li>
                <li className="rounded px-4 py-2">
                  <Link className="hover:underline" href="/">
                    Support
                  </Link>
                </li>
                <li className="rounded px-4 py-2">
                  <Link className="hover:underline" href="/">
                    Blog
                  </Link>
                </li>
                <li className="rounded px-4 py-2">
                  <Link className="hover:underline" href="/">
                    Careers
                  </Link>
                </li>
              </ul>
              <button className="hover:shadow-button mt-auto flex w-full items-center justify-center rounded-[28px] bg-brand py-2 text-base font-medium text-white transition hover:bg-brand/80">
                <FiDownload className="mr-3 text-xl" />
                Download for Mac
              </button>
              <RxCross2
                onClick={() => setIsOpen(false)}
                className="absolute top-8 right-6 cursor-pointer text-2xl"
              />
            </div>
            <GoThreeBars
              onClick={() => setIsOpen(true)}
              className="ml-4 cursor-pointer text-3xl text-white lg:hidden"
            />
          </nav>
        </header>
        <div className="relative z-[5] mx-auto flex max-w-6xl flex-col items-start px-5 pt-12 pb-[300px] md:items-center md:pt-[120px] md:pb-[160px]">
          <h1 className="__className_f7a229 text-2xl font-bold md:text-[56px]">
            Imagine a place...
          </h1>
          <p className="mt-5 max-w-3xl text-left text-base md:mt-10 md:text-center md:text-xl ">
            ...where you can belong to a school club, a gaming group, or a
            worldwide art community. Where just you and a handful of friends can
            spend time together. A place that makes it easy to talk every day
            and hang out more often.
          </p>
          <div className="mt-6 flex w-full flex-col items-start justify-center gap-6 md:flex-row md:items-center">
            <button className="hover:shadow-button flex items-center rounded-[28px] bg-white py-4 px-8 text-xl font-medium text-[#23272a] transition hover:text-brand">
              <FiDownload className="mr-3 text-2xl" />
              Download for Mac
            </button>
            <button className="hover:shadow-button hover:black-hover rounded-[28px] bg-[#23272a] py-4 px-8 text-xl font-medium text-white transition">
              Open Discord in your browser
            </button>
          </div>
        </div>
        <div className="absolute inset-0 h-full w-full">
          <img
            src="/images/clouds.svg"
            className="absolute bottom-0 left-1/2 top-auto z-0 ml-[-1280px] hidden max-w-[2560px] md:block"
          />
          <img
            src="/images/boot.svg"
            className="absolute bottom-0 z-0 ml-[-80px] md:left-1/2 md:ml-[-1000px]"
          />
          <img
            src="/images/chill.svg"
            className="absolute bottom-0 left-1/2 z-0 ml-[370px]"
          />
        </div>
      </div>
      <main className="text-[#23272a]">
        <div className="flex flex-col items-center">
          <div className="grid w-full max-w-[1260px] grid-cols-12 gap-5 py-20 px-5 md:py-[120px] md:px-[40px]">
            <img
              src="/images/group.svg"
              alt="group"
              className="col-span-12 md:col-span-7"
            />
            <div className="md:weird col-span-12 flex flex-col justify-center">
              <h2 className="text-xl font-extrabold leading-[120%] md:text-[48px]">
                Create an invite-only place where you belong
              </h2>
              <p className="mt-5 text-base leading-[1.625] md:text-xl">
                Discord servers are organized into topic-based channels where
                you can collaborate, share, and just talk about your day without
                clogging up a group chat.
              </p>
            </div>
          </div>
          <div className="flex w-full flex-col items-center bg-[#f6f6f6]">
            <div className="grid w-full max-w-[1260px] grid-cols-12 gap-5 py-20 px-5 md:py-[120px] md:px-[40px]">
              <img
                src="/images/voice.svg"
                alt="group"
                className="md:weird-3 order-1 col-span-12 md:order-2"
              />
              <div className="md:weird-2 order-2 col-span-12 flex flex-col justify-center md:order-1">
                <h2 className="text-xl font-extrabold leading-[120%] md:text-[48px]">
                  Where hanging out is easy
                </h2>
                <p className="mt-5 text-base leading-[1.625] md:text-xl">
                  Grab a seat in a voice channel when you’re free. Friends in
                  your server can see you’re around and instantly pop in to talk
                  without having to call.
                </p>
              </div>
            </div>
          </div>
          <div className="grid w-full max-w-[1260px] grid-cols-12 gap-5 py-20 px-5 md:py-[120px] md:px-[40px]">
            <img
              src="/images/graggle.svg"
              alt="group"
              className="col-span-12 md:col-span-7"
            />
            <div className="md:weird col-span-12 flex flex-col justify-center">
              <h2 className="mt-5 text-xl font-extrabold leading-[120%] md:mt-0 md:text-[48px]">
                From few to a fandom
              </h2>
              <p className="mt-5 text-base leading-[1.625] md:text-xl">
                Get any community running with moderation tools and custom
                member access. Give members special powers, set up private
                channels, and more.
              </p>
            </div>
          </div>
        </div>
        <div className="flex w-full flex-col items-center bg-[#f6f6f6] text-center">
          <div className="grid w-full max-w-[1260px] grid-cols-12 py-20 px-5 pb-[80px] md:py-[120px] md:px-[40px]">
            <div className="md:weird-4 col-span-12 flex w-full flex-col items-start md:items-center">
              <h2
                className="__className_f7a229 text-left text-2xl font-bold leading-[95%] md:text-center md:text-[40px]"
                // className={gintoFont.className}
                // style={{ fontWeight: 700, fontSize: 40, lineHeight: "95%" }}
              >
                RELIABLE TECH FOR STAYING CLOSE
              </h2>
              <p className="font-calc mt-5 text-left leading-[1.625] md:text-center">
                Low-latency voice and video feels like you’re in the same room.
                Wave hello over video, watch friends stream their games, or
                gather up and have a drawing session with screen share.
              </p>
            </div>
            <img
              src="/images/call.svg"
              alt="call"
              className="col-span-12 mt-5 w-full !max-w-[auto] md:mt-0"
            />
          </div>
          <div className="relative mb-[120px] flex w-full max-w-[1260px] flex-col items-center space-y-5 px-[40px] text-center">
            <div className="absolute top-0 flex w-full justify-center">
              <img src="/images/sparkles.svg" alt="sparkles" />
            </div>
            <h2 className="z-10 text-[32px] font-bold">
              Ready to start your journey?
            </h2>
            <button className="hover:shadow-button flex w-full items-center justify-center rounded-[28px] bg-brand py-4 px-8 text-xl font-medium text-white transition hover:bg-brand/90 md:w-auto">
              <FiDownload className="mr-3 text-2xl" />
              Download for Mac
            </button>
          </div>
        </div>
      </main>
      <footer className="flex justify-center bg-[#23272a]">
        <div className="w-full max-w-[1260px] px-5 pt-20 pb-16 md:px-[40px]">
          <div className="flex flex-col justify-between gap-5 border-b border-brand pb-10 md:flex-row">
            <div className="mr-28 space-y-5 uppercase text-brand">
              <h2
                className={gintoFont.className}
                style={{ fontWeight: 700, fontSize: 32 }}
              >
                Imagine a place
              </h2>
              <ul className="flex items-center space-x-4 text-[22px]">
                <li className="cursor-pointer text-white">
                  <BsTwitter />
                </li>
                <li className="cursor-pointer text-white">
                  <BsInstagram />
                </li>
                <li className="cursor-pointer text-white">
                  <BsFacebook />
                </li>
                <li className="cursor-pointer text-white">
                  <BsYoutube />
                </li>
              </ul>
            </div>
            <div className="mt-5 flex w-full flex-wrap justify-between gap-10 text-white md:gap-5">
              <ul className="flex min-w-[200px] flex-col space-y-2 md:min-w-[150px]">
                <h2 className="text-brand">Product</h2>
                <li className="cursor-pointer hover:underline">Download</li>
                <li className="cursor-pointer hover:underline">Nitro</li>
                <li className="cursor-pointer hover:underline">Status</li>
              </ul>
              <ul className="flex min-w-[200px] flex-col space-y-2 md:min-w-[150px]">
                <h2 className="text-brand">Company</h2>
                <li className="cursor-pointer hover:underline">About</li>
                <li className="cursor-pointer hover:underline">Jobs</li>
                <li className="cursor-pointer hover:underline">Branding</li>
                <li className="cursor-pointer hover:underline">Newsroom</li>
              </ul>
              <ul className="flex min-w-[200px] flex-col space-y-2 md:min-w-[150px]">
                <h2 className="text-brand">Resources</h2>
                <li className="cursor-pointer hover:underline">College</li>
                <li className="cursor-pointer hover:underline">Support</li>
                <li className="cursor-pointer hover:underline">Safety</li>
                <li className="cursor-pointer hover:underline">Blog</li>
                <li className="cursor-pointer hover:underline">Feedback</li>
                <li className="cursor-pointer hover:underline">Developers</li>
                <li className="cursor-pointer hover:underline">StreamKit</li>
                <li className="cursor-pointer hover:underline">Creators</li>
              </ul>
              <ul className="flex min-w-[200px] flex-col space-y-2 md:min-w-[150px]">
                <h2 className="text-brand">Policies</h2>
                <li className="cursor-pointer hover:underline">Terms</li>
                <li className="cursor-pointer hover:underline">Privacy</li>
                <li className="cursor-pointer hover:underline">
                  Cookie settings
                </li>
                <li className="cursor-pointer hover:underline">Guidelines</li>
                <li className="cursor-pointer hover:underline">
                  Acknowledgements
                </li>
                <li className="cursor-pointer hover:underline">Licenses</li>
                <li className="cursor-pointer hover:underline">Moderation</li>
              </ul>
            </div>
          </div>
          <div className="mt-10 flex items-center justify-between">
            <Link href="/">
              <img
                src="/logos/small_logo_white_RGB.svg"
                width={124}
                height={36}
              />
            </Link>
            <Link
              href="/signup"
              className="hover:shadow-button rounded-3xl bg-brand px-4 py-2 text-sm font-medium text-white transition hover:bg-brand/90"
            >
              Sign up
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
